name: "ForkLift"
description: "Keeps Minimal forks updated with their upstream couterparts"
branding:
  icon: "chevrons-right"
  color: "blue"
inputs:
  upstream_url:
    description: "Upstream URL. This MUST be public!"
    required: true
  upstream_branch:
    description: "Upstream Branch to Merge/Rebase"
    required: true
    default: "master"
  branch:
    description: "Branch to Merge/Rebase"
    required: true
    default: "master"
  method:
    description: "Method to use. Can be `merge`, `merge-ff-only` or `rebase`."
    required: true
    default: "rebase"
  sync_tags:
    description: "Sync Tags"
    default: "false"
    required: true
  args:
    description: "Extra arguments"
    default: ""
    required: false
runs:
  using: "docker"
  image: "src/Dockerfile"
  args:
    - '--method'
    - ${{ inputs.method }}
    - '--branch'
    - ${{ inputs.branch }}
    # Upstream
    - '--upstream-url'
    - ${{ inputs.upstream_url }}
    - '--upstream-branch'
    - ${{ inputs.upstream_branch }}
    # Extra
    - ${{ inputs.args }}
