name: "ForkLift"
description: "Keeps Minimal forks updated with their upstream counter part"
branding:
  icon: "chevrons-right"
  color: "blue"
inputs:
  upstream_url:
    description: "Upstream URL. This MUST be public!"
    required: true
  upstream_branch:
    description: "Upstream Branch to Merge/Rebase"
    required: true
    default: "master"
  branch:
    description: "Branch to Merge/Rebase"
    required: true
    default: "master"
  method:
    description: "Method to use. Can be `merge`, `merge-ff-only` or `rebase`."
    required: true
    default: "rebase"
  args:
    description: "Extra arguments"
    default: ""
    required: false
runs:
  using: "composite"
  steps:
  - name: forklift
    shell: bash
    run: |
      ./${{ github.action_path }}/forklift.sh \
      --method ${{ inputs.method }} \
      --branch ${{ inputs.branch }} \
      --upstream-url ${{ inputs.upstream_url }} \
      --upstream-branch ${{ inputs.upstream_branch }} \
      ${{ inputs.args }}
