name: build
on:
  push:
  pull_request:
jobs:
  # shellcheck
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: shellcheck
        run: make shellcheck
