name: build
on:
  push:
  pull_request:
jobs:
  # lint everything
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [docker-lint, shellcheck]
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: make ${{ matrix.linter }}
  # Build docker images
  docker:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: |
          make debug-vars
          make docker

      # - name: Docker Login to Registry (GitHub)
      #   run: echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
      #   env:
      #     DOCKER_USERNAME: tprasadtp
      #     DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      #   if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'

      - name: Docker Login to Registry (DockerHub)
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: tprasadtp
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name	== 'push'

      - name: Docker Push
        run: make docker-push
        if: github.event_name	== 'push'

      - name: Docker Cleanup
        run: |
          docker logout || true
          rm -f ${HOME}/.docker/config.json
        if: github.event_name	== 'push'
